version: "3"
services:
  flask:
    volumes:
      - ../../../envs:/home/app/envs:ro
      - ../../../src:/home/app/src:ro
      - ../../../web:/home/app/web:ro
    ports:
      - 5000:5000
    command: ["python3", "/home/app/src/run.py"]
  redis:
    ports:
      - 6379:6379
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
