version: "3"
services:
  flask:
    volumes:
      - ../../../src:/home/flask/src:ro
      - ../../../web:/home/flask/web:ro
    ports:
      - 5000:5000
    command: ["python", "/home/flask/src/run.py"]
