version: "3"
services:
  flask:
    build:
      context: ../../../
      dockerfile: ./server/docker/plexlib/flask/Dockerfile
    domainname: "${DOMAIN_NAME:-flask.local}"
    volumes:
      - ../../../envs:/home/flask/envs:ro
      - ${PLEX_MOVIES_ROOT:-/Volumes/Video/Movies}:/mnt/video/movies:ro
      - ${PLEX_TVSHOWS_ROOT:-/Volumes/Video/TV}:/mnt/video/tv_shows:ro
    depends_on:
      - redis
      - rabbitmq
  celery:
    build:
      context: ../../../
      dockerfile: ./server/docker/plexlib/celery/Dockerfile
    domainname: "${DOMAIN_NAME:-celery.local}"
    volumes:
      - ../../../envs:/home/celery/envs:ro
      - ${PLEX_MOVIES_ROOT:-/Volumes/Video/Movies}:/mnt/video/movies:ro
      - ${PLEX_TVSHOWS_ROOT:-/Volumes/Video/TV}:/mnt/video/tv_shows:ro
    depends_on:
      - redis
      - rabbitmq
  celerybeat:
    build:
      context: ../../../
      dockerfile: ./server/docker/plexlib/celerybeat/Dockerfile
    domainname: "${DOMAIN_NAME:-celerybeat.local}"
    volumes:
      - ../../../envs:/home/celery/envs:ro
    depends_on:
      - rabbitmq
  redis:
    image: "redis:alpine"
    domainname: "${DOMAIN_NAME:-redis.local}"
    ports:
      - 6379:6379
  rabbitmq:
    image: "rabbitmq:management-alpine"
    domainname: "${DOMAIN_NAME:-rabbitmq.local}"
    environment:
      - RABBITMQ_DEFAULT_USER=plexlib
      - RABBITMQ_DEFAULT_PASS=plexlib
      - RABBITMQ_DEFAULT_VHOST=plexlib
      - RABBITMQ_ERLANG_COOKIE='rabbitmq-cookie'
    ports:
      - 15672:15672
  nginx:
    image: "nginx:alpine"
    domainname: "${DOMAIN_NAME:-nginx.local}"
    ports:
      - 8888:8888
    volumes:
      - ../../../web:/usr/share/nginx/html:ro
      - ./nginx/plexlib.conf:/etc/nginx/conf.d/plexlib.conf:ro
    depends_on:
      - flask
