version: "3.2"
services:
  flask:
    image: willharris/plexlib:latest
    build:
      context: ../../../
      dockerfile: ./server/docker/plexlib/flask/Dockerfile
    domainname: "${DOMAIN_NAME:-flask.local}"
    expose:
      - 3031
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://plexlib:plexlib@rabbitmq/plexlib
    env_file:
      - ./plexlib-envs.txt
    volumes:
      - ${PLEXLIB_MOVIES_ROOT:-/Volumes/Video/Movies}:/mnt/video/movies:ro
      - ${PLEXLIB_TVSHOWS_ROOT:-/Volumes/Video/TV}:/mnt/video/tv_shows:ro
    depends_on:
      - redis
      - rabbitmq
  celery:
    image: willharris/plexlib:latest
    domainname: "${DOMAIN_NAME:-celery.local}"
    command: celery -A plexlib.tasks.celery worker --concurrency 1 --loglevel INFO
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://plexlib:plexlib@rabbitmq/plexlib
    env_file:
      - ./plexlib-envs.txt
    volumes:
      - ${PLEXLIB_MOVIES_ROOT:-/Volumes/Video/Movies}:/mnt/video/movies:ro
      - ${PLEXLIB_TVSHOWS_ROOT:-/Volumes/Video/TV}:/mnt/video/tv_shows:ro
    depends_on:
      - redis
      - rabbitmq
  celerybeat:
    image: willharris/plexlib:latest
    domainname: "${DOMAIN_NAME:-celerybeat.local}"
    command: celery -A plexlib.tasks.celery beat --loglevel INFO --schedule /tmp/celerybeat-schedule.db --pidfile /tmp/celerybeat.pid
    environment:
      - CELERY_BROKER_URL=amqp://plexlib:plexlib@rabbitmq/plexlib
    env_file:
      - ./plexlib-envs.txt
    depends_on:
      - rabbitmq
  redis:
    image: "redis:alpine"
    domainname: "${DOMAIN_NAME:-redis.local}"
    deploy:
      mode: global
  rabbitmq:
    image: "rabbitmq:management-alpine"
    domainname: "${DOMAIN_NAME:-rabbitmq.local}"
    environment:
      - RABBITMQ_DEFAULT_USER=plexlib
      - RABBITMQ_DEFAULT_PASS=plexlib
      - RABBITMQ_DEFAULT_VHOST=plexlib
      - RABBITMQ_ERLANG_COOKIE='rabbitmq-cookie'
    ports:
      - 15672:15672
    deploy:
      mode: global
  nginx:
    image: "nginx:alpine"
    domainname: "${DOMAIN_NAME:-nginx.local}"
    ports:
      - 8888:8888
    volumes:
      - ../../../web:/usr/share/nginx/html:ro
      - ./nginx/plexlib.conf:/etc/nginx/conf.d/plexlib.conf:ro
    depends_on:
      - flask
