version: "3"
services:
  flask:
    volumes:
      - ../../../envs:/home/app/envs:ro
      - ../../../src:/home/app/src:ro
      - ../../../web:/home/app/web:ro
    ports:
      - 5000:5000
    command: ["python", "/home/app/src/run.py"]
